<font face="Times New Roman" size="6">**Исследование сетевых параметров публичных DNS серверов**</font><br>

<font face="Times New Roman" size="4"><u>**Цель работы:**</u></font><br>
<font face="Times New Roman" size="4">Проанализировать сетевые параметры публичных DNS серверов, сделать мотивированный вывод о предпочтительных серверах</font><br><br>

<font face="Times New Roman" size="4"><u>**Исходные данные:**</u></font><br>
<font face="Times New Roman" size="3"><table>
| Устройство  | Виртуальная машина   | Операционная система| 
| ------------------------ | ------------------------- | --------------------|
| Asus UX330UA   | VMware Workstation Pro 15 |  Windows 10         |
</table></font>
<font face="Times New Roman" size="5"><u>**Используемое ПО:**</u></font><br>

<font face="Times New Roman" size="4">1. Rstudio IDE</font><br>
<font face="Times New Roman" size="4">2. Traceroute/tracert</font><br>
<font face="Times New Roman" size="4">3. Ping</font><br>
<font face="Times New Roman" size="4">4. 2ip</font><br>


<font face="Times New Roman" size="5"><u>**Исследуемые провайдеры DNS**</u></font>

<font face="Times New Roman" size="4">1. Google Public DNS</font><br>
<font face="Times New Roman" size="4">2. Cloudflare DNS</font><br>
<font face="Times New Roman" size="4">3. OpenDNS</font><br>
<font face="Times New Roman" size="4">4. FLEX</font><br>


<font face="Times New Roman" size="5"><u>**Варианты решения задачи**</u></font>

<font face="Times New Roman" size="4">1. Использовать утилиту tracert/traceroute(выберем этот вариант)</font><br>
<font face="Times New Roman" size="4">2. Использовать ручной поиск, без утилит</font><br>


<font face="Times New Roman" size="5"><u>**Общий план выполнения**</u></font>

<font face="Times New Roman" size="4">1. По исследуемым серверам собрать следующие данные:</font><br>
<font face="Times New Roman" size="4">1.1.маршрут</font><br>
<font face="Times New Roman" size="4">1.2.местоположение каждого узла маршрута к DNS-серверу</font><br>
<font face="Times New Roman" size="4">1.3.организацию, владеющую каждым узлом маршрута к DNS-серверу</font><br>
<font face="Times New Roman" size="4">1.4.среднюю RTT (round trip time) к DNS-серверу</font><br>
<font face="Times New Roman" size="4">2. Выделить те узлы маршрута, которые вносят наибольшую временную задержку при передаче</font><br>
<font face="Times New Roman" size="4">3. Сравнить сетевые параметры DNS серверов</font><br>

<font face="Times New Roman" size="5"><u>**Ход работы**</u></font>

<font face="Times New Roman" size="4"><u>**1.Google Public DNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 8.8.8.8

Трассировка маршрута к dns.google [8.8.8.8]
с максимальным числом прыжков 30:

  1     3 ms     2 ms     3 ms  192.168.1.1
  2    16 ms     4 ms     4 ms  100.80.0.1
  3     7 ms     2 ms     2 ms  10.1.120.18
  4    26 ms     3 ms     2 ms  10.1.120.25
  5     7 ms    16 ms     6 ms  10.1.120.82
  6     6 ms     1 ms     2 ms  10.1.120.51
  7    55 ms     6 ms     5 ms  188.191.127.209
  8     3 ms     2 ms    20 ms  10.1.120.42
  9     3 ms     8 ms     2 ms  10.1.120.194
 10     3 ms     3 ms     3 ms  213.5.104.5.dynamic.ufanet.ru [213.5.104.5]
 11    14 ms    57 ms    25 ms  72.14.220.188
 12     5 ms     5 ms     6 ms  108.170.250.99
 13    20 ms    21 ms    20 ms  172.253.66.116
 14    20 ms    23 ms    28 ms  172.253.66.108
 15    23 ms    47 ms    30 ms  216.239.62.107
 16     *        *        *     Превышен интервал ожидания для запроса.
 17     *        *        *     Превышен интервал ожидания для запроса.
 18     *        *        *     Превышен интервал ожидания для запроса.
 19     *        *        *     Превышен интервал ожидания для запроса.
 20     *        *        *     Превышен интервал ожидания для запроса.
 21     *        *        *     Превышен интервал ожидания для запроса.
 22     *        *        *     Превышен интервал ожидания для запроса.
 23     *        *        *     Превышен интервал ожидания для запроса.
 24     *        *        *     Превышен интервал ожидания для запроса.
 25    27 ms    24 ms    25 ms  dns.google [8.8.8.8]
 
```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
ping 8.8.8.8

Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время=25мс TTL=40
Ответ от 8.8.8.8: число байт=32 время=20мс TTL=40
Ответ от 8.8.8.8: число байт=32 время=49мс TTL=40
Ответ от 8.8.8.8: число байт=32 время=21мс TTL=40

Статистика Ping для 8.8.8.8:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 20мсек, Максимальное = 49 мсек, Среднее = 28 мсек
  
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 3го узла</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Не определен     |   -   | 
|  2   |100.80.0.1|     Лос-Анжелес, США       |    IANA     |  
 |  3   | 10.1.120.18 |      Лос-Анжелес, США       |IANA|
|  4     |          10.1.120.25                | Лос-Анжелес, США| IANA  | 
|  5   |          10.1.120.82                  | Лос-Анжелес, США| IANA  | 
|  6   |         10.1.120.51                |Лос-Анжелес, США| IANA  | 
|  7   |         188.191.127.209                   |РФ, Одинцово| VL-Telecom  |   
|  8 |        10.1.120.42               |   Лос-Анжелес, США                        |      IANA       |
|  9  |        10.1.120.194               |     Лос-Анжелес, США                       |       IANA      |    
|  10 |        213.5.104.5.dynamic.ufanet.ru [213.5.104.5]               |    РФ, Уфа                        |   JSC "Ufanet"          |           
|  11   |        72.14.220.188               |       США, Маунтин-Вью                     |     Google LLC        |       
|  12 |            108.170.250.99               |       США, Маунтин-Вью                     |       Google LLC       |      
|  13      |        172.253.66.116               |                            |         Google LLC     |   
|  14| 172.253.66.108               |         США, Маунтин-Вью                   |      Google LLC       |          
|  15   |        216.239.62.107               |              США              |     Google LLC        |  
|  16    |        Request timed out.               |                            |             |   
|  17    |        Request timed out.               |                            |             |   
|  18   |        Request timed out.               |                            |           
  |
|  19   |        Request timed out.               |                            |           
  |  
|  20   |        Request timed out.               |                            |           
  |  
|  21   |        Request timed out.               |                            |           
  |  
|  22   |        Request timed out.               |                            |           
  |  
|  23   |        Request timed out.               |                            |           
  |  
|  24   |        Request timed out.               |                            |           
  |   
|  25   |       dns.google [8.8.8.8]              |       США, Нью-Йорк        | Google LLC  |    
</table></font>

<font face="Times New Roman" size="4"><u>**2.OpenDNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
tracert 208.67.222.222

Трассировка маршрута к resolver1.opendns.com [208.67.222.222]
с максимальным числом прыжков 30:

  1     5 ms     2 ms     3 ms  192.168.1.1
  2     3 ms     5 ms    15 ms  100.80.0.1
  3     3 ms     1 ms     3 ms  10.1.120.18
  4     5 ms     7 ms     6 ms  10.1.120.25
  5    11 ms     9 ms     3 ms  10.1.120.82
  6     4 ms     3 ms     2 ms  10.1.120.51
  7    12 ms     9 ms     5 ms  188.191.127.209
  8     3 ms     3 ms    26 ms  10.1.120.42
  9     3 ms     5 ms     3 ms  10.1.120.194
 10     4 ms     4 ms     4 ms  213.5.104.5.dynamic.ufanet.ru [213.5.104.5]
 11     5 ms     4 ms     3 ms  msk-m9-cr2.bvi2064.rascom.as20764.net [81.27.252.150]
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *       22 ms  8-2-3-402.ear2.Stockholm2.Level3.net [212.73.250.201]
 14    52 ms    48 ms    46 ms  ae-2-3207.edge6.Amsterdam1.Level3.net [4.69.162.218]
 15    48 ms    46 ms    46 ms  unknown.Level3.net [212.72.47.62]
 16    49 ms    50 ms    49 ms  resolver1.opendns.com [208.67.222.222]

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping  208.67.222.222

Обмен пакетами с 208.67.222.222 по с 32 байтами данных:
Ответ от 208.67.222.222: число байт=32 время=47мс TTL=50
Ответ от 208.67.222.222: число байт=32 время=47мс TTL=50
Ответ от 208.67.222.222: число байт=32 время=50мс TTL=50
Ответ от 208.67.222.222: число байт=32 время=49мс TTL=50

Статистика Ping для 208.67.222.222:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 47мсек, Максимальное = 50 мсек, Среднее = 48 мсек
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 3го узла</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      -       |   -    | 
|  2   |100.80.0.1|     Лос-Анжелес, США       |    IANA     |  
|  3   | 10.1.120.18 |     Лос-Анжелес, США     |IANA |
|  4 | 10.1.120.25  |   Лос-Анжелес, США     | IANA  | 
|  5     |          10.1.120.82              |Лос-Анжелес, США| IANA   | 
|  6    |          10.1.120.51               |Лос-Анжелес, США | IANA   | 
|  7    |        188.191.127.209                |РФ, Одинцово| VL-Telecom  | 
|  8     |         10.1.120.42                 |Лос-Анжелес, США | 	IANA |   
|  9  |          10.1.120.194                |      Лос-Анжелес, США        |  IANA    | 
|  10   |213.5.104.5.dynamic.ufanet.ru [213.5.104.5]|     -      |    -     |  
|  11   | msk-m9-cr2.bvi2064.rascom.as20764.net [81.27.252.150] |     Лос-Анжелес, США       |IANA|
|  12 | Превышен интервал ожидания для запроса.  |       |  | 
|  13     |          8-2-3-402.ear2.Stockholm2.Level3.net [212.73.250.201]                 |Ирландия,Бланчардстаун| Stockholm Customer Links2  | 
|  14    |         ae-2-3207.edge6.Amsterdam1.Level3.net [4.69.162.218]                 |США| 	Level 3 Parent, LLC  | 
|  15    |       unknown.Level3.net [212.72.47.62]               |Великобритания| Level (3) Communications International  | 
|  16     |         resolver1.opendns.com [208.67.222.222]                  |США, Сан-Франциско| 	Cisco OpenDNS, LLC  | 
</table></font>

<font face="Times New Roman" size="4"><u>**3.Cloudflare DNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 1.1.1.1

Трассировка маршрута к one.one.one.one [1.1.1.1]
с максимальным числом прыжков 30:

  1     3 ms     9 ms     3 ms  192.168.1.1
  2     8 ms    25 ms     6 ms  100.80.0.1
  3    32 ms     5 ms     4 ms  10.1.120.18
  4     7 ms     6 ms     2 ms  10.1.120.25
  5     6 ms     4 ms     *     10.1.120.82
  6     2 ms     2 ms     2 ms  10.1.120.51
  7     8 ms     3 ms     6 ms  188.191.127.209
  8     8 ms     4 ms     3 ms  10.1.120.42
  9     3 ms     2 ms     2 ms  10.1.120.194
 10     3 ms     4 ms     3 ms  213.5.104.5.dynamic.ufanet.ru [213.5.104.5]
 11     4 ms     7 ms     4 ms  msk-m9-cr2.bvi2064.rascom.as20764.net [81.27.252.150]
 12     5 ms     4 ms     4 ms  172.68.8.252
 13    11 ms    15 ms    17 ms  one.one.one.one [1.1.1.1]

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 1.1.1.1

Обмен пакетами с 1.1.1.1 по с 32 байтами данных:
Ответ от 1.1.1.1: число байт=32 время=5мс TTL=53
Ответ от 1.1.1.1: число байт=32 время=4мс TTL=53
Ответ от 1.1.1.1: число байт=32 время=4мс TTL=53
Ответ от 1.1.1.1: число байт=32 время=4мс TTL=53

Статистика Ping для 1.1.1.1:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 4мсек, Максимальное = 5 мсек, Среднее = 4 мсек
    
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 1го узла</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      -        |   -    | 
|  2   |100.80.0.1|     Лос-Анжелес, США       |    IANA     |  
|  3   | 10.1.120.18|     Лос-Анжелес, США        |IANA|
|  4 | 10.1.120.25  |   Лос-Анжелес, США      | 	IANA | 
|  5     |         10.1.120.82                 |Лос-Анжелес, США | IANA  | 
|  6    |          10.1.120.51                  |Лос-Анжелес, США| IANA  | 
|  7    |        188.191.127.209             |РФ, Одинцово| VL-Telecom | 
|  8     |         10.1.120.42                  |Лос-Анжелес, США | IANA  | 
|  9 | 10.1.120.194 |   Лос-Анжелес, США      | 	Internet Assigned Numbers Authority | 
|  10     |          213.5.104.5.dynamic.ufanet.ru [213.5.104.5]                |-| -  | 
|  11    |          msk-m9-cr2.bvi2064.rascom.as20764.net [81.27.252.150]                  |Лос-Анжелес, США| IANA  | 
|  12    |        172.68.8.252                |Украина, Киев| Cloudflare, Inc. | 
|  13     |         one.one.one.one [1.1.1.1]                  |Австралия|APNIC and Cloudflare DNS Resolver project 	  | 

</table></font>


<font face="Times New Roman" size="4"><u>**4.Vlasiha**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 79.174.47.2

Трассировка маршрута к vltele.com [79.174.47.2]
с максимальным числом прыжков 30:

  1     3 ms     4 ms     2 ms  192.168.1.1
  2     3 ms     4 ms     2 ms  100.80.0.1
  3     6 ms     4 ms     3 ms  10.1.120.34
  4     3 ms     5 ms     2 ms  10.1.120.102
  5     4 ms     2 ms     6 ms  vltele.com [79.174.47.2]

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 79.174.47.2

Обмен пакетами с 79.174.47.2 по с 32 байтами данных:
Ответ от 79.174.47.2: число байт=32 время=3мс TTL=60
Ответ от 79.174.47.2: число байт=32 время=17мс TTL=60
Ответ от 79.174.47.2: число байт=32 время=2мс TTL=60
Ответ от 79.174.47.2: число байт=32 время=2мс TTL=60

Статистика Ping для 79.174.47.2:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 2мсек, Максимальное = 17 мсек, Среднее = 6 мсек
    
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 2го узла.</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      -        |   -    | 
|  2   |100.80.0.1|     Лос-Анжелес, США       |    IANA     |  
|  3   | 10.1.120.34|     Лос-Анжелес, США      |IANA|
|  4 | 10.1.120.102  |   Лос-Анжелес, США      | 	IANA | 
|  5 | vltele.com [79.174.47.2]  |   РФ, Одинцово      | 	Vlasiha | 


</table></font>

<font face="Times New Roman" size="5"><u>**Сравнительная диаграмма**</u></font>


<font face="Times New Roman" size="5"><u>Используемые цвета:</u></font>

<font face="Times New Roman" size="4">1. Google DNS - красный</font><br>
<font face="Times New Roman" size="4">2. OpenDNS - желтый </font><br>
<font face="Times New Roman" size="4">2. Cloudflare DNS - зеленый</font><br>
<font face="Times New Roman" size="4">4. Vltelecom - голубой</font><br>

```{r, echo=FALSE}
x <- c(0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130)
y <- c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.5,13)
x_1 <- c(25,20,49,21)
y_1 <- c(1,2,3,4)
x_2 <- c(47,47,50,49)
y_2 <- c(1,2,3,4)
x_3 <- c(5,4,4,4)
y_3 <- c(1,2,3,4)
x_4 <- c(3,17,2,2)
y_4 <- c(1,2,3,4)

plot(y,x,main = "Сравнительная диаграмма RTT к серверам", xlab = "Step", ylab = "RTT",type = "n")
points(y_1,x_1, col = "black")
lines(y_1,x_1, col = "black")
points(y_2,x_2, col = "green")
lines(y_2,x_2, col = "green")
points(y_3,x_3, col = "orange")
lines(y_3,x_3, col = "orange")
points(y_4,x_4, col = "blue")
lines(y_4,x_4, col = "blue")
```


<font face="Times New Roman" size="5"><u>**Оценка результатов:**</u></font><br>
<font face="Times New Roman" size="4">Меньше всего времени потребовалось для обмена пакетов для Vltelecom и OpenDNS.</font><br>


<font face="Times New Roman" size="5"><u>**Вывод:**</u></font><br>
<font face="Times New Roman" size="4">Я проанализировала сетевые параметры публичных DNS серверов.</font><br>


